function [config] = get_studydetails()

    config = [];

    % The location of the downloaded data
    % eg: config.datadir = '/home/disk3/ajquinn/ds000117/';
    config.datadir = ''; % <- edit this line

    % The location of the downloaded scripts directory
    % config.scriptdir = '/home/disk3/ajquinn/HMM_frontiers_download/';
    config.scriptdir = ''; % <- edit this line

    % The location to save the analyses generated by these scripts
    % config.analysisdir = '/home/disk3/ajquinn/HMM_face_analysis/';
    config.analysisdir = ''; % <- edit this line

    % Run some sanity checks

    % Are the paths specified?
    if isempty(config.datadir)
        warning('Please specify the location of the datadir inside utils/+utils/get_studydetails.');
    end
    if isempty(config.scriptdir)
        warning('Please specify the location of the scriptdir inside utils/+utils/get_studydetails.');
    end
    if isempty(config.analysisdir)
        warning('Please specify the location of the analysisdir inside utils/+utils/get_studydetails.');
    end

    % Do all the folders exist?
    if exist( config.datadir, 'dir' ) == 0
        error('datadir path in utils/+utils/get_studydetails.m not found: %s', config.datadir);
    end
    if exist( config.scriptdir, 'dir' ) == 0
        error('studydir path in utils/+utils/get_studydetails.m not found: %s', config.scriptdir);
    end
    if exist( config.analysisdir, 'dir' ) == 0
        error('analysisdir path in utils/+utils/get_studydetails.m not found: %s', config.analysisdir);
    end
